CREATE TABLE IF NOT EXISTS lab_test_catalog (
  id VARCHAR(191) PRIMARY KEY,
  laboratoryId VARCHAR(191) NOT NULL,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(191) NOT NULL,
  category VARCHAR(100) NOT NULL,
  sampleType VARCHAR(80) NOT NULL,
  preparationInstructions TEXT NULL,
  turnaroundHours INT NOT NULL DEFAULT 24,
  price DECIMAL(12,2) NOT NULL,
  homeCollectionCharge DECIMAL(12,2) NOT NULL DEFAULT 0,
  taxRate DECIMAL(5,2) NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_lab_test_code (laboratoryId, code),
  INDEX idx_lab_catalog_active (laboratoryId, active, category),
  CONSTRAINT fk_lab_catalog_facility FOREIGN KEY (laboratoryId) REFERENCES hospital(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lab_test_package (
  id VARCHAR(191) PRIMARY KEY,
  laboratoryId VARCHAR(191) NOT NULL,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(191) NOT NULL,
  description TEXT NULL,
  listPrice DECIMAL(12,2) NOT NULL DEFAULT 0,
  packagePrice DECIMAL(12,2) NOT NULL,
  discountPercent DECIMAL(5,2) NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_lab_package_code (laboratoryId, code),
  CONSTRAINT fk_lab_package_facility FOREIGN KEY (laboratoryId) REFERENCES hospital(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lab_test_package_item (
  packageId VARCHAR(191) NOT NULL,
  testId VARCHAR(191) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (packageId, testId),
  CONSTRAINT fk_package_item_package FOREIGN KEY (packageId) REFERENCES lab_test_package(id) ON DELETE CASCADE,
  CONSTRAINT fk_package_item_test FOREIGN KEY (testId) REFERENCES lab_test_catalog(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS testrequest (
  id VARCHAR(191) PRIMARY KEY,
  patientId VARCHAR(191) NOT NULL,
  hospitalId VARCHAR(191) NOT NULL,
  doctorId VARCHAR(191) NULL,
  referringHospitalId VARCHAR(191) NULL,
  catalogTestId VARCHAR(191) NULL,
  packageId VARCHAR(191) NULL,
  testType VARCHAR(191) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Pending Collection',
  priority VARCHAR(30) NOT NULL DEFAULT 'Normal',
  sampleId VARCHAR(80) NULL UNIQUE,
  sampleCollectedAt DATETIME(3) NULL,
  assignedTo VARCHAR(191) NULL,
  rejectionReason TEXT NULL,
  homeCollection TINYINT(1) NOT NULL DEFAULT 0,
  collectionAddress TEXT NULL,
  preparationInstructions TEXT NULL,
  unitPrice DECIMAL(12,2) NOT NULL DEFAULT 0,
  homeCollectionCharge DECIMAL(12,2) NOT NULL DEFAULT 0,
  abnormalFlag VARCHAR(30) NULL,
  clinicalNotes TEXT NULL,
  invoiceId VARCHAR(191) NULL,
  reportRecordId VARCHAR(191) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_testrequest_lab_status (hospitalId, status, createdAt),
  INDEX idx_testrequest_patient (patientId, createdAt),
  INDEX idx_testrequest_referrer (referringHospitalId, status),
  CONSTRAINT fk_testrequest_patient FOREIGN KEY (patientId) REFERENCES patient(id) ON DELETE RESTRICT,
  CONSTRAINT fk_testrequest_lab FOREIGN KEY (hospitalId) REFERENCES hospital(id) ON DELETE RESTRICT,
  CONSTRAINT fk_testrequest_doctor FOREIGN KEY (doctorId) REFERENCES doctor(id) ON DELETE SET NULL,
  CONSTRAINT fk_testrequest_referrer FOREIGN KEY (referringHospitalId) REFERENCES hospital(id) ON DELETE SET NULL,
  CONSTRAINT fk_testrequest_catalog FOREIGN KEY (catalogTestId) REFERENCES lab_test_catalog(id) ON DELETE SET NULL,
  CONSTRAINT fk_testrequest_package FOREIGN KEY (packageId) REFERENCES lab_test_package(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS testrequest_status_history (
  id VARCHAR(191) PRIMARY KEY,
  testRequestId VARCHAR(191) NOT NULL,
  status VARCHAR(50) NOT NULL,
  notes TEXT NULL,
  updatedBy VARCHAR(191) NULL,
  location VARCHAR(191) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_test_history_request (testRequestId, createdAt),
  CONSTRAINT fk_test_history_request FOREIGN KEY (testRequestId) REFERENCES testrequest(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sample (
  id VARCHAR(191) PRIMARY KEY,
  sampleType VARCHAR(80) NOT NULL,
  patientId VARCHAR(191) NOT NULL,
  testRequestId VARCHAR(191) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Registered',
  hospitalId VARCHAR(191) NOT NULL,
  barcodeValue VARCHAR(191) NOT NULL UNIQUE,
  collectedAt DATETIME(3) NULL,
  receivedAt DATETIME(3) NULL,
  processedAt DATETIME(3) NULL,
  disposedAt DATETIME(3) NULL,
  temperature VARCHAR(40) NULL,
  containerType VARCHAR(80) NULL,
  rejectionReason TEXT NULL,
  assignedTo VARCHAR(191) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_sample_lab_status (hospitalId, status, createdAt),
  CONSTRAINT fk_sample_patient FOREIGN KEY (patientId) REFERENCES patient(id) ON DELETE RESTRICT,
  CONSTRAINT fk_sample_request FOREIGN KEY (testRequestId) REFERENCES testrequest(id) ON DELETE CASCADE,
  CONSTRAINT fk_sample_lab FOREIGN KEY (hospitalId) REFERENCES hospital(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS billing_catalog (
  id VARCHAR(191) PRIMARY KEY,
  facilityId VARCHAR(191) NOT NULL,
  facilityType VARCHAR(30) NOT NULL,
  code VARCHAR(40) NULL,
  name VARCHAR(191) NOT NULL,
  category VARCHAR(80) NOT NULL,
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  taxRate DECIMAL(5,2) NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_billing_catalog_facility (facilityId, active),
  CONSTRAINT fk_billing_catalog_facility FOREIGN KEY (facilityId) REFERENCES hospital(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS billing_invoice (
  id VARCHAR(191) PRIMARY KEY,
  invoiceNo VARCHAR(50) NOT NULL UNIQUE,
  patientId VARCHAR(191) NOT NULL,
  facilityId VARCHAR(191) NOT NULL,
  facilityType VARCHAR(30) NOT NULL,
  facilityName VARCHAR(191) NOT NULL,
  encounterType VARCHAR(30) NOT NULL DEFAULT 'OPD',
  appointmentId VARCHAR(191) NULL,
  admissionId VARCHAR(191) NULL,
  claimId VARCHAR(191) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  subtotal DECIMAL(12,2) NOT NULL,
  discountTotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  taxTotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  insuranceDeduction DECIMAL(12,2) NOT NULL DEFAULT 0,
  depositAdjusted DECIMAL(12,2) NOT NULL DEFAULT 0,
  totalAmount DECIMAL(12,2) NOT NULL,
  amountPaid DECIMAL(12,2) NOT NULL DEFAULT 0,
  patientPayable DECIMAL(12,2) NOT NULL DEFAULT 0,
  dueDate DATE NULL,
  notes TEXT NULL,
  finalizedAt DATETIME(3) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_billing_invoice_patient (patientId, createdAt),
  INDEX idx_billing_invoice_facility (facilityId, createdAt),
  CONSTRAINT fk_billing_invoice_patient FOREIGN KEY (patientId) REFERENCES patient(id) ON DELETE RESTRICT,
  CONSTRAINT fk_billing_invoice_facility FOREIGN KEY (facilityId) REFERENCES hospital(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS billing_invoice_item (
  id VARCHAR(191) PRIMARY KEY,
  invoiceId VARCHAR(191) NOT NULL,
  catalogItemId VARCHAR(191) NULL,
  sourceType VARCHAR(50) NULL,
  sourceId VARCHAR(191) NULL,
  name VARCHAR(191) NOT NULL,
  category VARCHAR(80) NOT NULL,
  serviceDate DATETIME(3) NULL,
  quantity DECIMAL(10,2) NOT NULL,
  unitPrice DECIMAL(12,2) NOT NULL,
  discount DECIMAL(12,2) NOT NULL DEFAULT 0,
  taxRate DECIMAL(5,2) NOT NULL DEFAULT 0,
  taxAmount DECIMAL(12,2) NOT NULL DEFAULT 0,
  lineTotal DECIMAL(12,2) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_billing_item_invoice (invoiceId),
  CONSTRAINT fk_billing_item_invoice FOREIGN KEY (invoiceId) REFERENCES billing_invoice(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hospital_room (
  id VARCHAR(191) PRIMARY KEY,
  hospitalId VARCHAR(191) NOT NULL,
  ward VARCHAR(100) NOT NULL,
  roomNumber VARCHAR(50) NOT NULL,
  bedNumber VARCHAR(50) NOT NULL,
  roomType VARCHAR(80) NOT NULL,
  dailyRate DECIMAL(12,2) NOT NULL,
  nursingRatePerDay DECIMAL(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_hospital_bed (hospitalId, ward, roomNumber, bedNumber),
  INDEX idx_room_availability (hospitalId, status, roomType),
  CONSTRAINT fk_room_hospital FOREIGN KEY (hospitalId) REFERENCES hospital(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS admission (
  id VARCHAR(191) PRIMARY KEY,
  admissionNo VARCHAR(50) NOT NULL UNIQUE,
  patientId VARCHAR(191) NOT NULL,
  hospitalId VARCHAR(191) NOT NULL,
  doctorId VARCHAR(191) NULL,
  roomId VARCHAR(191) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ADMITTED',
  admissionType VARCHAR(30) NOT NULL DEFAULT 'IPD',
  diagnosis TEXT NULL,
  admittedAt DATETIME(3) NOT NULL,
  expectedDischargeAt DATETIME(3) NULL,
  dischargedAt DATETIME(3) NULL,
  depositAmount DECIMAL(12,2) NOT NULL DEFAULT 0,
  depositAdjusted DECIMAL(12,2) NOT NULL DEFAULT 0,
  insuranceClaimId VARCHAR(191) NULL,
  finalInvoiceId VARCHAR(191) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_admission_hospital_status (hospitalId, status, admittedAt),
  INDEX idx_admission_patient (patientId, admittedAt),
  CONSTRAINT fk_admission_patient FOREIGN KEY (patientId) REFERENCES patient(id) ON DELETE RESTRICT,
  CONSTRAINT fk_admission_hospital FOREIGN KEY (hospitalId) REFERENCES hospital(id) ON DELETE RESTRICT,
  CONSTRAINT fk_admission_doctor FOREIGN KEY (doctorId) REFERENCES doctor(id) ON DELETE SET NULL,
  CONSTRAINT fk_admission_room FOREIGN KEY (roomId) REFERENCES hospital_room(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS admission_charge (
  id VARCHAR(191) PRIMARY KEY,
  admissionId VARCHAR(191) NOT NULL,
  category VARCHAR(80) NOT NULL,
  description VARCHAR(255) NOT NULL,
  serviceDate DATETIME(3) NOT NULL,
  quantity DECIMAL(10,2) NOT NULL DEFAULT 1,
  unitPrice DECIMAL(12,2) NOT NULL,
  discount DECIMAL(12,2) NOT NULL DEFAULT 0,
  taxRate DECIMAL(5,2) NOT NULL DEFAULT 0,
  sourceType VARCHAR(50) NULL,
  sourceId VARCHAR(191) NULL,
  createdBy VARCHAR(191) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_admission_charge (admissionId, serviceDate),
  CONSTRAINT fk_admission_charge_admission FOREIGN KEY (admissionId) REFERENCES admission(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS discharge_summary (
  id VARCHAR(191) PRIMARY KEY,
  admissionId VARCHAR(191) NOT NULL UNIQUE,
  finalDiagnosis TEXT NOT NULL,
  clinicalCourse TEXT NULL,
  proceduresPerformed TEXT NULL,
  conditionAtDischarge TEXT NULL,
  dischargeMedicines TEXT NULL,
  followUpInstructions TEXT NULL,
  followUpDate DATE NULL,
  preparedBy VARCHAR(191) NULL,
  finalizedAt DATETIME(3) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_discharge_admission FOREIGN KEY (admissionId) REFERENCES admission(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS insurance_policy (
  id VARCHAR(191) PRIMARY KEY,
  patientId VARCHAR(191) NOT NULL,
  insurerName VARCHAR(191) NOT NULL,
  tpaName VARCHAR(191) NULL,
  policyNumber VARCHAR(100) NOT NULL,
  memberId VARCHAR(100) NULL,
  planName VARCHAR(191) NULL,
  coverageAmount DECIMAL(14,2) NULL,
  validFrom DATE NOT NULL,
  validUntil DATE NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  isPrimary TINYINT(1) NOT NULL DEFAULT 0,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_policy_number (patientId, policyNumber),
  INDEX idx_policy_patient_active (patientId, status, validUntil),
  CONSTRAINT fk_policy_patient FOREIGN KEY (patientId) REFERENCES patient(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS insurance_claim (
  id VARCHAR(191) PRIMARY KEY,
  claimNumber VARCHAR(80) NOT NULL UNIQUE,
  policyId VARCHAR(191) NOT NULL,
  patientId VARCHAR(191) NOT NULL,
  hospitalId VARCHAR(191) NOT NULL,
  admissionId VARCHAR(191) NULL,
  invoiceId VARCHAR(191) NULL,
  claimType VARCHAR(30) NOT NULL DEFAULT 'CASHLESS',
  status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
  requestedAmount DECIMAL(14,2) NOT NULL DEFAULT 0,
  approvedAmount DECIMAL(14,2) NOT NULL DEFAULT 0,
  rejectedAmount DECIMAL(14,2) NOT NULL DEFAULT 0,
  patientPayable DECIMAL(14,2) NOT NULL DEFAULT 0,
  authorizationNumber VARCHAR(100) NULL,
  submittedAt DATETIME(3) NULL,
  decidedAt DATETIME(3) NULL,
  rejectionReason TEXT NULL,
  notes TEXT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_claim_facility_status (hospitalId, status, createdAt),
  INDEX idx_claim_patient (patientId, createdAt),
  CONSTRAINT fk_claim_policy FOREIGN KEY (policyId) REFERENCES insurance_policy(id) ON DELETE RESTRICT,
  CONSTRAINT fk_claim_patient FOREIGN KEY (patientId) REFERENCES patient(id) ON DELETE RESTRICT,
  CONSTRAINT fk_claim_hospital FOREIGN KEY (hospitalId) REFERENCES hospital(id) ON DELETE RESTRICT,
  CONSTRAINT fk_claim_admission FOREIGN KEY (admissionId) REFERENCES admission(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS claim_document (
  id VARCHAR(191) PRIMARY KEY,
  claimId VARCHAR(191) NOT NULL,
  documentType VARCHAR(80) NOT NULL,
  fileName VARCHAR(255) NOT NULL,
  mimeType VARCHAR(100) NOT NULL,
  storagePath TEXT NOT NULL,
  fileHash CHAR(64) NOT NULL,
  uploadedBy VARCHAR(191) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_claim_document (claimId, documentType),
  CONSTRAINT fk_claim_document_claim FOREIGN KEY (claimId) REFERENCES insurance_claim(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS digital_document (
  id VARCHAR(191) PRIMARY KEY,
  documentNo VARCHAR(80) NOT NULL UNIQUE,
  documentType VARCHAR(50) NOT NULL,
  entityType VARCHAR(50) NOT NULL,
  entityId VARCHAR(191) NOT NULL,
  patientId VARCHAR(191) NULL,
  facilityId VARCHAR(191) NULL,
  verificationToken CHAR(64) NOT NULL UNIQUE,
  contentHash CHAR(64) NOT NULL,
  signerName VARCHAR(191) NULL,
  signerRegistrationNo VARCHAR(100) NULL,
  signatureText TEXT NULL,
  issuedAt DATETIME(3) NOT NULL,
  revokedAt DATETIME(3) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_digital_document_entity (entityType, entityId),
  INDEX idx_digital_document_patient (patientId, issuedAt)
);
