CREATE TABLE IF NOT EXISTS user_activity_session (
  id VARCHAR(191) NOT NULL,
  userId VARCHAR(191) NOT NULL,
  startedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  lastSeenAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  endedAt DATETIME(3) NULL,
  durationSeconds INT UNSIGNED NOT NULL DEFAULT 0,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  INDEX idx_user_activity_user (userId),
  INDEX idx_user_activity_last_seen (lastSeenAt),
  CONSTRAINT fk_user_activity_user
    FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE
);
